# Generated by Django 3.0.4 on 2020-09-27 05:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default='True')),
                ('game_over', models.BooleanField(default='False')),
                ('user1_token', models.CharField(max_length=15)),
                ('user2_token', models.CharField(max_length=15)),
                ('user1_move', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=22)),
                ('user2_move', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=22)),
                ('matrix1', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=7), size=8)),
            ],
        ),
    ]
